name: CI
on: push
jobs:
  tests:
    strategy:
      matrix:
        ruby-version:
          - 2.4.x
          - 2.5.x
          - 2.6.x

    name: ${{ format('Tests (Ruby {0})', matrix.ruby-version) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install gem dependencies
        run: gem install bundler -v 1.15.3 && bundler install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rake
